version: '3.1'

services:
  db:
    image: mysql:8.0.29-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: app_db
    ports:
      - 6033:3306
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./init:/home
    networks:
      - appnet
    container_name: db-project-mysql-compose

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - appnet
    container_name: db-project-phpmyadmin-compose

volumes:
  mysql_volume:

networks:
  appnet:
    driver: bridge