version: '3.1'

services:
  db:
    image: mysql:8.0.29-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: app_db
    ports:
      - 6033:3306
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./init:/home
    networks:
      - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    volumes:
      - phpmyadmin_volume

volumes:
  mysql_volume:
  phpmyadmin_volume:

networks:
  appnet:
    driver: bridge